In [19]:
# This file generates gestation cdf from files 'all_cols_train_win_1.csv' and
# 'all_cols_test_win_1.csv'
# Author: Luna Xia 

import numpy as np
from scipy.stats import norm
trn1 = np.genfromtxt('all_cols_train_win_1.csv', delimiter=',') 
tst1 = np.genfromtxt('all_cols_test_win_1.csv', delimiter=',') 
gest_trn1 = trn1[:,6]
gest_tst1 = tst1[:,6]
trn1_cdf = norm.cdf(gest_trn1,276,4)
tst1_cdf = norm.cdf(gest_tst1,276,4)
np.savetxt("trn_win1_gestcdf.csv", trn1_cdf, fmt='%.3f', delimiter=",")
np.savetxt("tst_win1_gestcdf.csv", tst1_cdf, fmt='%.3f', delimiter=",")

[274. 274. 274. 274. 273.]
[0.30853754 0.30853754 0.30853754 0.30853754 0.22662735]
[271. 271. 271. 271. 271.]
[0.10564977 0.10564977 0.10564977 0.10564977 0.10564977]
